### ISSUE TITLE
正方形容器中的图片保持比例并最大化显示

### ISSUE THREAD

**Issue by Dream4ever** [Dream4ever/Knowledge-Base#114]
## 需求描述

在做一个页面的时候，对一批图片（缩略图）有如下要求：

- 包含图片的正方形容器尺寸为 160px * 160px
- 图片长边的尺寸为 160px
- 图片保持原始比例

## 解决方案

```css
.img-container {
  width: 160px;
  height: 160px;
}

.img-container>img {
  object-fit: contain;
}
```

最关键的，其实就是这个 `object-fit` 属性。该属性值分别为 `contain`、`none`、`scale-down` 时，均能使图片最大化显示的同时保持原始比例。

## 参考资料

- [object-fit: CSS | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)
