### ISSUE TITLE
使元素保持长宽比

### ISSUE THREAD

**Issue by Dream4ever** [Dream4ever/Knowledge-Base#194]
## 解决过程

Google `css set element height same as width`。

[Height equal to dynamic width (CSS fluid layout) [duplicate]](https://stackoverflow.com/questions/5445491/height-equal-to-dynamic-width-css-fluid-layout)

只需要给元素本身设置 CSS 样式即可:

```css
.some_element {
    position: relative;
    width: 20%;
    height: 0;
    padding-bottom: 20%;
}
```
