### ISSUE TITLE
鼠须管输入法设置 - Mac 版

### ISSUE THREAD

**Issue by Dream4ever** [Dream4ever/Knowledge-Base#77]
## 功能配置

```yaml
# ~/Library/Rime/default.custom.yaml 该文件保存的位置。这一行不写配置内容，而是写上注释，是为了避免有些文件在文件头中写入了 BOM，而影响配置文件的正常读取
patch: # 覆盖默认设置
  schema_list: # 列出所要使用的输入方案，未列出的不使用。各方案的名称可在 /Library/Input Methods/Squirrel.app/Contents/SharedSupport 中找到，拼音输入方案为该目录下的 *.schema.yaml 文件
    - schema: double_pinyin_mspy
  switcher:
    hotkeys:
      - "Control+s" # 默认的 Ctrl+` 和 VSCode 的调出终端的快捷键相冲突，改成 Ctrl+s 调出输入法菜单。这里设置的快捷键 `Ctrl+s`，两侧要用英文双引号括起来。并且字母 `s` 要小写，如果这里写成了大写，则在使用快捷键的时候，也必须按着 `Shift` 键才行
  key_binder:
    bindings:
      - when: paging
        accept: bracketleft # 左括号往左翻页
        send: Page_Up
      - when: has_menu
        accept: bracketright # 右括号往右翻页
        send: Page_Down
      - when: paging
        accept: comma # 左括号往左翻页
        send: Page_Up
      - when: has_menu
        accept: period # 右括号往右翻页
        send: Page_Down
      - when: paging
        accept: minus # 左括号往左翻页
        send: Page_Up
      - when: has_menu
        accept: equal # 右括号往右翻页
        send: Page_Down
  menu:
    page_size: 9 # 设置候选字字数
  punctuator: # 设置按键所对应的直接上屏字符
    half_shape:
      '<' : '《'
      '>' : '》'
      '/' : '、'
      '~' : '~'
      '*' : '*'
```

## 界面设置

```yaml
# ~/Library/Rime/squirrel.custom.yaml 该文件保存的位置
patch:
  app_options:
    com.runningwithcrayons.Alfred-3: # Alfrea 3 中默认开启英文模式
      ascii_mode: true
    com.googlecode.iterm2: # iTerm 2 中默认开启英文模式
      ascii_mode: true
  style: # 设置输入法的界面
    color_scheme: luna # 选择要使用的样式，可用的样式列表在 /Library/Input Methods/Squirrel.app/Contents/SharedSupport/squirrel.yaml 这个文件的 preset_color_schemes 字段中
    corner_radius: 10 # 设置界面的圆角半径，默认的直角界面不太好看
    font_point: 16 # 设置输入法界面上字体的字号，根据自己喜欢的字号大小来设置即可
    horizontal: true # 该字段的值设置为 `true` 时，候选字横向排开。默认情况下，候选字是纵向显示的
```

## 拼音方案设置

```yaml
# ~/Library/Rime/double_pinyin_mspy.custom.yaml 该文件保存的位置
patch:
  switches:
    - name: ascii_mode # 从其它拼音方案切换过来时，默认为中文模式
      reset: 0
      states: [ 中文, 西文 ]
    - name: full_shape
      states: [ 半角, 全角 ]
    - name: simplification # 默认简体输入
      reset: 1
      states: [ 漢字, 汉字 ]
```

## 参考链接：

- [Rime 定製指南](https://github.com/rime/home/wiki/CustomizationGuide)
- [鼠须管，“神级”输入法](http://www.ifanr.com/156409)
- [Rime 输入法有比较现成的设置吗？](https://www.zhihu.com/question/20871256)
- [鼠须管输入法 傻瓜版配置 - 基于 rime_pro 增强包](https://segmentfault.com/a/1190000005754706)
- [安装及配置 Mac 上的 Rime 输入法——鼠鬚管 (Squirrel)](http://www.dreamxu.com/install-config-squirrel/) 
- [Schema.yaml 詳解](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md)
